# Tags a new release with a new version, and automatically publishes its
# sources and binaries into the release tag.
name: Tag and Release

on:
  schedule:
    - cron: '0 0 10 * *'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Test"
        run: "bazel test --test_output=errors //... //:repo.doc_extract"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
      - name: Get release tag
        id: get_version
        run: echo "VERSION=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV
      - name: Get repo name
        id: get_repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: "Prepare source archive release artifact"
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"
          exclusions: '*.git* /*node_modules/* .editorconfig /bazel-*'

      - name: "Prepare docs archive release artifact"
        run: |
          find bazel-bin/ -name "*.doc_extract.binaryproto" -print0 \
          | tar -czvf ${{ env.REPO_NAME }}-${{ env.VERSION }}.docs.tar.gz \
            --null -T - --transform 's/^bazel-bin\///g'

      - name: "Upload source archive"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          allowUpdates: true
          artifacts: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip, ${{ env.REPO_NAME }}-${{ env.VERSION }}.docs.tar.gz"

  release:
    needs: tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["386", "amd64"]
        os: ["linux"]
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-${{ matrix.arch }}-bazel-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-bazel-
      - name: "Test"
        run: "bazel test --test_output=errors //..."
      - name: "Build binaries for ${{ matrix.os }}_${{ matrix.arch }}"
        run: "bazel build --platforms=@rules_go//go/toolchain:${{ matrix.os }}_${{ matrix.arch}} --//cmd/lit2md:name_part_from_command_line=${{ matrix.os }}-${{ matrix.arch }} //cmd/lit2md:zip"
      - name: Find version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true
      - name: "Publish ${{ matrix.os }}_${{ matrix.arch }}"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "bazel-bin/cmd/lit2md/lit2md-${{ matrix.os }}-${{ matrix.arch }}.zip"
          tag: ${{ steps.tag_version.outputs.previous_tag }}


  # This workflow waits for binary artifacts to be published.
  publish:
    needs: tag
    uses: ./.github/workflows/publish.yml
    with:
      tag_name: ${{ needs.tag.outputs.tag_name }}
    secrets:
      BCR_PUBLISH_TOKEN: ${{ secrets.BCR_PUBLISH_TOKEN }}

